---
abstract: 'Command line interface to run QC steps'
author:
  - 'Wellcome Trust Sanger Institute'
build_requires:
  Config::Tiny: 0
  English: 0
  File::Compare: 0
  File::Find: 0
  FindBin: 0
  HTGT::DBFactory: 0
  Test::More: 0.88
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTGT-QC-Common
requires:
  Array::Compare: 0
  Bio::EnsEMBL::Registry: 0
  Bio::EnsEMBL::Variation::Utils::BaseVepPlugin: 0
  Bio::Perl: 0
  Bio::Seq: 0
  Bio::SeqFeature::Generic: 0
  Bio::SeqIO: 0
  Bio::SeqUtils: 0
  CSV::Writer: 0
  Carp: 0
  Config::Scoped: 0
  Const::Fast: 0
  Data::Dump: 0
  Data::Dumper: 0
  Data::UUID: 0
  Date::Parse: 0
  DesignCreate::Util::BWA: 0
  DesignCreate::Util::Primer3: 0
  EngSeqBuilder: 0
  Exporter: 0
  Fcntl: 0
  File::Find::Rule: 0
  File::Temp: 0
  File::Which: 0
  Getopt::Long: 0
  IO::Handle: 0
  IPC::Run: 0
  IPC::System::Simple: 0
  Iterator::Simple: 0
  JSON: 0
  LIMS2::REST::Client: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Log4perl: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::App::Cmd: 0
  MooseX::App::Cmd::Command: 0
  MooseX::ClassAttribute: 0
  MooseX::Log::Log4perl: 0
  MooseX::Params::Validate: 0
  MooseX::StrictConstructor: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Path::Class::MoreCoercions: 0
  Parse::BooleanLogic: 0
  Path::Class: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Throwable::Error: 0
  Try::Tiny: 0
  WWW::JSON: 0
  WebAppCommon::Util::EnsEMBL: 0
  WebAppCommon::Util::FarmJobRunner: 0
  YAML: 0
  YAML::Any: 0
  base: 0
  constant: 0
  feature: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 0.050
